# Generated by Django 3.1.7 on 2021-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoecolor',
            name='color_name',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('indigo', 'indigo'), ('violet', 'violet'), ('white', 'white'), ('black', 'black')], max_length=9),
        ),
    ]
