# Generated by Django 3.1.7 on 2021-03-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoeapp', '0002_auto_20210323_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoetype',
            name='style',
            field=models.CharField(choices=[('sneaker', 'sneaker'), ('boot', 'boot'), ('sandal', 'sandal'), ('dress', 'dress'), ('other', 'other')], max_length=9),
        ),
    ]
